baseURL = "https://will-kelly.github.io/"
languageCode = "en-us"
title = "Will Kelly"
theme = "introduction"
publishDir = "docs"


[params]
  name = "Will Kelly"
  description = "Freelance Tech Writer. Content Strategist. DevOps Explainer."
  # Optional image path
  profilePicture = "img/will.jpg"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/will-Kelly"

[[params.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/willkelly"

[menu]

[[menu.main]]
  name = "About"
  url = "#about"

[[menu.main]]
  name = "Projects"
  url = "#projects"

[[menu.main]]
  name = "Contact"
  url = "#contact"

